language: node_js

sudo: false

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  

install:
  - npm install
  - npm install coveralls

script:
  - npm run coverage
  - npm run lint

after_success:
  - nyc report --reporter=text-lcov | coveralls

cache:
  directories:
    - node_modules

os:
  - linux
  - osx
  - windows
